---

- name: Ensure the Supervisor service is running
  service:
    name: supervisor
    state: started
    enabled: yes

- name: Create the Supervisor config file
  template:
    src: supervisor_config.j2
    dest: /etc/supervisor/conf.d/{{ application_name }}.conf
    backup: yes

- name: Re-read the Supervisor config files
  supervisorctl:
    name: "{{ application_name }}"
    state: present
