version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: whitenoise
    versions:
    - ">= 5.a"
    - "< 6"
- package-ecosystem: npm
  directory: "/components"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: bootstrap
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: bootstrap-social
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: bootswatch
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: chosen
    versions:
    - ">= 1.a"
    - "< 2"
  - dependency-name: drmonty-datatables-responsive
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: flot
    versions:
    - ">= 2.a"
    - "< 3"
  - dependency-name: flot
    versions:
    - ">= 3.a"
    - "< 4"
  - dependency-name: flot
    versions:
    - ">= 4.a"
    - "< 5"
  - dependency-name: fullcalendar
    versions:
    - ">= 5.a"
    - "< 6"
  - dependency-name: startbootstrap-sb-admin-2
    versions:
    - ">= 3.a"
    - "< 4"
  - dependency-name: startbootstrap-sb-admin-2
    versions:
    - ">= 4.a"
    - "< 5"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  target-branch: dev
  
