---
sensitiveCodepaths:
  - 'dojo/object/urls.py'
  - 'dojo/object/views.py'
  - 'dojo/announcement/*.py'
  - 'dojo/api_v2/*.py'
  - 'dojo/api_v2/**/*.py'
  - 'dojo/authorization/*.py'
  - 'dojo/db_migrations/*.py'
  - 'dojo/endpoint/*.py'
  - 'dojo/engagement/*.py'
  - 'dojo/finding/*.py'
  - 'dojo/finding_group/*.py'
  - 'dojo/group/*.py'
  - 'dojo/importers/*.py'
  - 'dojo/importers/**/*.py'
  - 'dojo/jira_link/*.py'
  - 'dojo/metrics/*.py'
  - 'dojo/note_type/*.py'
  - 'dojo/notes/*.py'
  - 'dojo/product/*.py'
  - 'dojo/product_type/*.py'
  - 'dojo/reports/*.py'
  - 'dojo/risk_acceptance/*.py'
  - 'dojo/search/*.py'
  - 'dojo/templates/*.html'
  - 'dojo/templates/**/*.html'
  - 'dojo/templatetags/*.py'
  - 'dojo/test/*.py'
  - 'dojo/tool_config/*.py'
  - 'dojo/tool_product/*.py'
  - 'dojo/tool_type/*.py'
  - 'dojo/user/*.py'
  - 'dojo/apps.py'
  - 'dojo/celery.py'
  - 'dojo/context_processors.py'
  - 'dojo/decorators.py'
  - 'dojo/filters.py'
  - 'dojo/forms.py'
  - 'dojo/middleware.py'
  - 'dojo/models.py'
  - 'dojo/okta.py'
  - 'dojo/pipeline.py'
  - 'dojo/remote_user.py'
  - 'dojo/tasks.py'
  - 'dojo/urls.py'
  - 'dojo/utils.py'
  - 'dojo/views.py'
  - 'dojo/wsgi.py'
  - 'docker/environments/*.env'
  - 'docker/extra_settings'
  - 'docker/entrypoint-celery-beat.sh'
  - 'docker/entrypoint-celery-worker.sh'
  - 'docker/entrypoint-initializer.sh'
  - 'docker/entrypoint-first-boot.sh'
  - 'docker/entrypoint-nginx.sh'
  - 'docker/entrypoint-uwsgi.sh'
  - 'docker/wait-for-it.sh'
allowedAuthors:
  usernames:
    - mtesauro
    - devGregA
    - grendel513
    - cneill
    - Maffooch
    - blakeaowens
    - kiblik
    - dsever
    - dogboat
    - hblankenship
notificationList:
  - '@mtesauro'
  - '@grendel513'
