---
version: '3.8'
services:
  integration-tests:
    build:
      context: ./
      dockerfile: Dockerfile.integration-tests
    image: "defectdojo/defectdojo-integration-tests:${INTEGRATION_TESTS_VERSION:-latest}"
    profiles: 
      - mysql-rabbitmq
      - mysql-redis
      - postgres-rabbitmq
      - postgres-redis
    depends_on:
      - nginx
      - uwsgi
    entrypoint: ['/wait-for-it.sh', '${DD_DATABASE_HOST}:${DD_DATABASE_PORT}', '-t', '30', '--', '/app/docker/entrypoint-integration-tests.sh']
    volumes:
      - '.:/app:z'
      - "defectdojo_media_integration_tests:${DD_MEDIA_ROOT:-/app/media}"
    environment:
      DD_BASE_URL: 'http://nginx:8080/'
      DD_ADMIN_USER: "${DD_ADMIN_USER:-admin}"
      DD_ADMIN_PASSWORD: "${DD_ADMIN_PASSWORD:-AdminsLoveIntegrationtests!}"
      DD_INTEGRATION_TEST_FILENAME: "${DD_INTEGRATION_TEST_FILENAME}"
  nginx:
    volumes:
      - defectdojo_media_integration_tests:/usr/share/nginx/html/media
  uwsgi:
    entrypoint: ['/wait-for-it.sh', '${DD_DATABASE_HOST}:${DD_DATABASE_PORT}', '-t', '30', '--', '/entrypoint-uwsgi-dev.sh']
    volumes:
      - '.:/app:z'
      - defectdojo_media_integration_tests:${DD_MEDIA_ROOT:-/app/media}
    environment:
      DD_DEBUG: 'True'
      DD_DATABASE_URL: ${DD_TEST_DATABASE_URL}
      DD_SECRET_KEY: "${DD_SECRET_KEY:-.}"
      DD_EMAIL_URL: "smtp://mailhog:1025"
  celerybeat:
    environment:
      DD_DATABASE_URL: ${DD_TEST_DATABASE_URL}
  celeryworker:
    environment:
      DD_DATABASE_URL: ${DD_TEST_DATABASE_URL}
  initializer:
    environment:
      DD_INITIALIZE: 'true'
      DD_DATABASE_URL: ${DD_TEST_DATABASE_URL}
      DD_ADMIN_PASSWORD: "${DD_ADMIN_PASSWORD:-AdminsLoveIntegrationtests!}"
      DD_SECRET_KEY: "${DD_SECRET_KEY:-.}"
    volumes:
      - '.:/app:z'
  mysql:
    ports:
      - target: ${DD_DATABASE_PORT}
        published: ${DD_DATABASE_PORT}
        protocol: tcp
        mode: host
    environment:
      MYSQL_DATABASE: ${DD_TEST_DATABASE_NAME}
    volumes:
      - defectdojo_data_integration_tests:/var/lib/mysql
  postgres:
    ports:
      - target: ${DD_DATABASE_PORT}
        published: ${DD_DATABASE_PORT}
        protocol: tcp
        mode: host
    environment:
      POSTGRES_DB: ${DD_TEST_DATABASE_NAME}
    volumes:
      - defectdojo_postgres_integration_tests:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:v1.0.1@sha256:8d76a3d4ffa32a3661311944007a415332c4bb855657f4f6c57996405c009bea
    ports:
      - target: 1025
        published: 1025
        protocol: tcp
        mode: host
volumes:
  defectdojo_data_integration_tests: {}
  defectdojo_postgres_integration_tests: {}
  defectdojo_media_integration_tests: {}
