---
services:
  nginx: !reset
  uwsgi:
    build:
      target: django-unittests
    entrypoint: ['/wait-for-it.sh', '${DD_DATABASE_HOST:-postgres}:${DD_DATABASE_PORT:-5432}', '-t', '30', '--', '/app/docker/entrypoint-unit-tests.sh']
    volumes:
      - '.:/app:z'
      - "defectdojo_media_unit_tests:${DD_MEDIA_ROOT:-/app/media}"
    depends_on: !override
      postgres:
        condition: service_started
    environment:
      PYTHONWARNINGS: error  # We are strict about Warnings during testing
      DD_DEBUG: 'False'
      DD_LOG_LEVEL: 'ERROR'
      DD_TEST_DATABASE_NAME: ${DD_TEST_DATABASE_NAME:-test_defectdojo}
      DD_DATABASE_NAME: ${DD_TEST_DATABASE_NAME:-test_defectdojo}
      DD_DATABASE_ENGINE: ${DD_DATABASE_ENGINE:-django.db.backends.postgresql}
      DD_DATABASE_HOST: ${DD_DATABASE_HOST:-postgres}
      DD_DATABASE_PORT: ${DD_DATABASE_PORT:-5432}
      DD_CELERY_BROKER_SCHEME: 'sqla+sqlite'
      DD_CELERY_BROKER_USER: ''
      DD_CELERY_BROKER_PASSWORD: ''
      DD_CELERY_BROKER_HOST: ''
      DD_CELERY_BROKER_PORT: "-1"
      DD_CELERY_BROKER_PATH: '/dojo.celerydb.sqlite'
      DD_CELERY_BROKER_PARAMS: ''
      DD_JIRA_EXTRA_ISSUE_TYPES: 'Vulnerability' # Shouldn't trigger a migration error
  celerybeat: !reset
  celeryworker: !reset
  initializer: !reset
  postgres:
    ports:
      - target: ${DD_DATABASE_PORT:-5432}
        published: ${DD_DATABASE_PORT:-5432}
        protocol: tcp
        mode: host
    environment:
      POSTGRES_DB: ${DD_TEST_DATABASE_NAME:-test_defectdojo}
    volumes:
      - defectdojo_postgres_unit_tests:/var/lib/postgresql/data
  valkey: !reset
  "webhook.endpoint":
    image: mccutchen/go-httpbin:2.18.3@sha256:3992f3763e9ce5a4307eae0a869a78b4df3931dc8feba74ab823dd2444af6a6b
volumes:
  defectdojo_postgres_unit_tests: {}
  defectdojo_media_unit_tests: {}
