dependencies:
  - name: mysql
    version: 1.6.9
    repository: "@stable"
    condition: mysql.enabled
  - name: postgresql
    version: 9.8.11
    repository: "@bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: 8.7.0
    repository: "@bitnami"
    condition: rabbitmq.enabled
  - name: redis
    version: 12.0.0
    repository: "@bitnami"
    condition: redis.enabled
