{{- $fullName := include "defectdojo.fullname" . -}}
{{- $redisScheme := include "redis.scheme" . -}}
{{- $defaultBrokerParams := ternary "ssl_cert_reqs=optional" "" (eq "rediss" $redisScheme) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- with .Values.extraAnnotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
data:
  DD_ADMIN_USER: {{ .Values.admin.user | default "admin" }}
  DD_ADMIN_MAIL: {{ .Values.admin.Mail | default "admin@defectdojo.local" }}
  DD_ADMIN_FIRST_NAME: {{ .Values.admin.FirstName | default "Admin" }}
  DD_ADMIN_LAST_NAME: {{ .Values.admin.LastName | default "User" }}
  DD_ALLOWED_HOSTS: {{ include "django.allowed_hosts" . }}
  DD_SITE_URL: {{ .Values.siteUrl | default "http://localhost:8080" }}
  DD_CELERY_BROKER_SCHEME: {{ template "redis.scheme" . }}
  DD_CELERY_BROKER_USER: ''
  DD_CELERY_BROKER_HOST: {{ template "redis.hostname" . }}
  DD_CELERY_BROKER_PORT: '{{ template "redis.port" . }}'
  DD_CELERY_BROKER_PARAMS: '{{ template "redis.params" . }}'
  DD_CELERY_BROKER_PATH: '{{ .Values.celery.path | default "//" }}'
  DD_CELERY_LOG_LEVEL: {{ .Values.celery.logLevel }}
  DD_CELERY_WORKER_POOL_TYPE: {{ .Values.celery.worker.appSettings.poolType | default "solo" }}
  DD_CELERY_WORKER_AUTOSCALE_MIN: '{{ if eq .Values.celery.worker.appSettings.poolType "prefork" }}{{ .Values.celery.worker.appSettings.autoscaleMin | default "2" }}{{ end }}'
  DD_CELERY_WORKER_AUTOSCALE_MAX: '{{ if eq .Values.celery.worker.appSettings.poolType "prefork" }}{{ .Values.celery.worker.appSettings.autoscaleMax | default "8" }}{{ end }}'
  DD_CELERY_WORKER_CONCURRENCY: '{{ if eq .Values.celery.worker.appSettings.poolType "prefork" }}{{ .Values.celery.worker.appSettings.concurrency | default "8" }}{{ end }}'
  DD_CELERY_WORKER_PREFETCH_MULTIPLIER: '{{ if eq .Values.celery.worker.appSettings.poolType "prefork" }}{{ .Values.celery.worker.appSettings.prefetchMultiplier | default "128" }}{{ end }}'
  DD_DATABASE_ENGINE: django.db.backends.postgresql
  DD_DATABASE_HOST: {{ template "postgresql.hostname" . }}
  DD_DATABASE_PORT: '{{ .Values.postgresql.primary.service.ports.postgresql }}'
  DD_DATABASE_USER: {{ .Values.postgresql.auth.username }}
  DD_DATABASE_NAME: {{ .Values.postgresql.auth.database }}
  DD_INITIALIZE: '{{ .Values.initializer.run }}'
  DD_UWSGI_ENDPOINT: /run/defectdojo/uwsgi.sock
  DD_UWSGI_HOST: localhost
  DD_UWSGI_PASS: unix:///run/defectdojo/uwsgi.sock
  DD_UWSGI_NUM_OF_PROCESSES: '{{ .Values.django.uwsgi.appSettings.processes | default 4 }}'
  DD_UWSGI_NUM_OF_THREADS: '{{ .Values.django.uwsgi.appSettings.threads | default 4 }}'
  {{- if  .Values.django.uwsgi.appSettings.maxFd }}
  DD_UWSGI_MAX_FD: '{{ .Values.django.uwsgi.appSettings.maxFd }}'
  {{- end }}
  DD_DJANGO_METRICS_ENABLED: '{{ .Values.monitoring.enabled }}'
  NGINX_METRICS_ENABLED: '{{ .Values.monitoring.enabled }}'
  METRICS_HTTP_AUTH_USER: {{ .Values.monitoring.user | default "monitoring" }}
{{- if  .Values.django.uwsgi.certificates.enabled }}
  REQUESTS_CA_BUNDLE: {{ .Values.django.uwsgi.certificates.certMountPath }}{{ .Values.django.uwsgi.certificates.certFileName }}
{{- end }}
{{- with .Values.extraConfigs }}
  {{- toYaml . | nindent 2 }}
{{- end }}
