{{- if .Values.extraSecrets -}}
{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-extrasecrets
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
    {{- with .Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.secretAnnotations .Values.annotations }}
  annotations:
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
{{- range $key, $value  := .Values.extraSecrets }}
{{ $key | indent 2}}: {{ $value | b64enc }}
{{- end }}
{{- end }}
