{{- if .Values.createPostgresqlHaSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresqlha.postgresql.existingSecret }}
  labels:
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
    {{- with .Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: "pre-install"
    helm.sh/hook-delete-policy: "before-hook-creation"
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- if .Values.postgresqlha.postgresql.password }}
  postgresql-password: {{ .Values.postgresqlha.postgresql.password | b64enc | quote }}
  postgresql-postgres-password: {{ .Values.postgresqlha.postgresql.password | b64enc | quote }}
{{- else }}
  {{- $postgresRandomPassword := randAlphaNum 16 | b64enc | quote }}
  postgresql-password: {{ $postgresRandomPassword }}
  postgresql-postgres-password: {{ $postgresRandomPassword }}
{{- end }}
{{- if .Values.postgresqlha.postgresql.repmgrPassword }}
  repmgr-password: {{ .Values.postgresqlha.postgresql.repmgrPassword | b64enc | quote }}
{{- else }}
  {{- $repmgrRandomPassword := randAlphaNum 16 | b64enc | quote }}
  repmgr-password: {{ $repmgrRandomPassword }}
{{- end }}
{{- end }}
