---
application_name: 'DefectDojo'
root_pass: 'r00tr00t'

# The Linux user account that DefectDojo will run under
dd_user: 'dd'
dd_user_pass: 'th1sisasup3rs3cur3passw0rd12345'

# MySQL settings
dd_sql_user: 'dd'
dd_sql_pass: 'pl34se$replace@these^stupid&passwords'
dd_sql_db: 'dd'

# Defines where the DefectDojo application will be installed
dd_install_dir: /usr/share/django-DefectDojo

# Defines the folder where DefectDojo's virtualenv will be stored
venv_dir: /home/{{ dd_user }}/.venvs/{{ application_name }}

# Set up the Django/DefectDojo superuser
dd_super_user: 'root'
dd_super_user_pass: 'An0th3r@SuPeR@Secure@PASSWORD'
dd_super_user_email: 'root@localhost'

# Repo link for DefectDojo
dd_git_repo: 'https://github.com/rackerlabs/django-DefectDojo.git'

# Gunicorn settings
gunicorn_num_workers: 3
gunicorn_timeout: 120
gunicorn_port: 9999
gunicorn_log_file: '{{ dd_install_dir }}/gunicorn.log'
