name: "Build Docker Images For Testing"

on:
  # inspired by https://github.com/orgs/community/discussions/26801 we take the runs-on as parameter so we can run arm64 on native hardwarde
  workflow_dispatch:
    inputs:
        platform:
          type: string
          default: "linux/amd64"
  workflow_call:
    inputs:
        platform:
          type: string
          default: "linux/amd64"

jobs:
  build:
    name: Build Docker Images
    runs-on: ${{ inputs.platform ==  'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    strategy:
      matrix:
        # integration tests are only build (and run) on debian linux/amd64
        docker-image: [django, nginx, integration-tests]
        os: [alpine, debian]
        platform: ["${{ inputs.platform }}"]
        exclude:
            - docker-image: integration-tests
              os: alpine
            - docker-image: integration-tests
              platform: linux/arm64

    steps:
      # Replace slashes so we can use this in filenames
      - name: Set-platform
        run: |
          platform=${{ inputs.platform }}
          echo "PLATFORM=${platform//\//-}" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Read Docker Image Identifiers
        id: read-docker-image-identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build
        id: docker_build
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        timeout-minutes: 15
        env:
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        with:
          context: .
          push: false
          tags: defectdojo/defectdojo-${{ matrix.docker-image }}:${{ matrix.os }},${{ env.IMAGE_REPOSITORY }}/defectdojo-${{ matrix.docker-image }}:${{ matrix.os }}
          file: Dockerfile.${{ matrix.docker-image }}-${{ matrix.os }}
          outputs: type=docker,dest=${{ matrix.docker-image }}-${{ matrix.os }}-${{ env.PLATFORM }}_img

      # export docker images to be used in next jobs below
      - name: Upload image ${{ matrix.docker-image }} as artifact
        timeout-minutes: 15
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: built-docker-image-${{ matrix.docker-image }}-${{ matrix.os }}-${{ env.PLATFORM }}
          path: ${{ matrix.docker-image }}-${{ matrix.os }}-${{ env.PLATFORM }}_img
          retention-days: 1
