name: "Build Docker Images For Testing"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    # build with docker so we can use layer caching
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker-image: [django, nginx, integration-tests]
        os: [alpine, debian]
        exclude:
          - docker-image: integration-tests
            os: alpine

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Read Docker Image Identifiers
        id: read-docker-image-identifiers
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0
        with:
          buildkitd-flags: --debug
          driver-opts: image=moby/buildkit:master # needed to get the fix for https://github.com/moby/buildkit/issues/2426
          
      - name: Build
        id: docker_build
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        timeout-minutes: 10
        env:
          DOCKER_BUILD_CHECKS_ANNOTATIONS: false
        with:
          context: .
          push: false
          tags: defectdojo/defectdojo-${{ matrix.docker-image }}:${{ matrix.os }}
          file: Dockerfile.${{ matrix.docker-image }}-${{ matrix.os }}
          outputs: type=docker,dest=${{ matrix.docker-image }}-${{ matrix.os }}_img

      # export docker images to be used in next jobs below
      - name: Upload image ${{ matrix.docker-image }} as artifact
        timeout-minutes: 10
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: built-docker-image-${{ matrix.docker-image }}-${{ matrix.os }}
          path: ${{ matrix.docker-image }}-${{ matrix.os }}_img
          retention-days: 1
