name: "Detect Merge Conflicts"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
      - master
      - bugfix
      - release/*

  pull_request_target:
    types: [synchronize]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: check if prs are conflicted
        # we experience a high error rate so we allow this to fail but still have the check become green on the PR
        continue-on-error: true
        uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # v3.0.3
        with:
          dirtyLabel: "conflicts-detected"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This pull request has conflicts, please resolve those before we can evaluate the pull request."
          commentOnClean: "Conflicts have been resolved. A maintainer will review the pull request shortly."
