name: "Release-2: Tag, Release, Push"

env:
  GIT_USERNAME: "DefectDojo release bot"
  GIT_EMAIL: "dojo-release-bot@users.noreply.github.com"

on:
  workflow_dispatch:
    inputs:
      # the actual branch that can be chosen on the UI is made irrelevant by further steps
      # because someone will forget one day to change it.
      release_number:
        description: 'Release version (x.y.z format)'
        default: "0.0.6"
        required: true

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: master

      - name: Configure git
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: Create new tag ${{ github.event.inputs.release_number }}
        # at this point, the PR from the 1st workflow is merged into master.
        run: |
        #   git tag -a ${{ github.event.inputs.release_number }} -m "[bot] release ${{ github.event.inputs.release_number }}"
        #   git push origin ${{ github.event.inputs.release_number }}

  release-helm-chart:
    needs: tag
    uses: ./.github/workflows/release-x-manual-helm-chart.yml
    with:
      release_number: ${{ github.event.inputs.release_number }}
    secrets: inherit

  release-docker-containers:
    needs: tag
    uses: ./.github/workflows/release-x-manual-docker-containers.yml
    with:
      release_number: ${{ github.event.inputs.release_number }}
    secrets: inherit

  merge-digests:
    needs: release-docker-containers
    uses: ./.github/workflows/release-x-merge-digests.yml
    secrets: inherit

  release-drafter:
    needs: release-docker-containers
    uses: ./.github/workflows/release-drafter.yml
    with:
      version: ${{ github.event.inputs.release_number }}
    secrets: inherit
