---
name: "release-X: Release helm chart"

env:
  GIT_USERNAME: "DefectDojo release bot"
  GIT_EMAIL: "dojo-release-bot@users.noreply.github.com"
on:
  workflow_dispatch:
    inputs:
      # the actual branch that can be chosen on the UI is made irrelevant by further steps
      # because someone will forget one day to change it.
      release_number:
        type: string
        description: 'Release number'
        required: true
  workflow_call:
    inputs:
      # the actual branch that can be chosen on the UI is made irrelevant by further steps
      # because someone will forget one day to change it.
      release_number:
        type: string
        description: 'Release number'
        required: true

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: master
          fetch-depth: 0
      
      # This action is deprecated. Not sure if it is even being used anymore...
      # - name: Get upload URL
      #   id: get-upload-url
      #   uses: pdamianik/release-tag-to-upload-url-action@v1.0.1
      #   with:
      #     tag: ${{ github.event.inputs.release_number }}
      #     token: ${{ github.token }}
      
      - name: Configure git
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
      
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
      
      - name: Configure HELM repos
        run: |-
             helm repo add bitnami https://charts.bitnami.com/bitnami
             helm dependency list ./helm/defectdojo
             helm dependency update ./helm/defectdojo
      
      - name: Add yq
        uses: mikefarah/yq@4839dbbf80445070a31c7a9c1055da527db2d5ee # v4.44.6

      - name: Pin version docker version
        id: pin_image
        run: |-
          yq --version
          yq -i '.tag="${{ github.event.inputs.release_number }}"'  helm/defectdojo/values.yaml
          echo "Current image tag:`yq -r '.tag' helm/defectdojo/values.yaml`"

      - name: Package Helm chart
        id: package-helm-chart
        run: |
          mkdir build
          helm package helm/defectdojo/ --destination ./build
          echo "chart_version=$(ls build | cut -d '-' -f 2 | sed 's|\.tgz||')" >> $GITHUB_ENV
      
      - name: Create release ${{ github.event.inputs.release_number }}
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # v2.2.1
        with:
          name: '${{ github.event.inputs.release_number }} ðŸŒˆ'
          tag_name: ${{ github.event.inputs.release_number }}
          body: Run the release drafter to populate the release notes.
          draft: true
          prerelease: false
          files: ./build/defectdojo-${{ env.chart_version }}.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: DefectDojo/django-DefectDojo
      
      - name: Update Helm repository index
        id: update-helm-repository-index
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git remote update
          git fetch --all
          git stash
          git checkout helm-charts
          git pull
          if [ ! -f ./index.yaml ]; then
            helm repo index ./build --url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${{ github.event.inputs.release_number }}/"
          else
            helm repo index ./build --url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${{ github.event.inputs.release_number }}/" --merge ./index.yaml
          fi
          cp -f ./build/index.yaml ./index.yaml
          git add ./index.yaml
          git commit -m "Update index.yaml"
          git push -u origin helm-charts
