name: Release Drafter

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          The version to be associated with the GitHub release that's created or updated.
          This will override any version calculated by the release-drafter.
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        description: |
          The version to be associated with the GitHub release that's created or updated.
          This will override any version calculated by the release-drafter.
        required: true

jobs:
  # Update the notes in the release drafter first
  # If the following jobs fail, then we will at least have some release notes present
  update_release_draft:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: release-drafter/release-drafter@v6.0.0
        with:
          version: ${{ github.event.inputs.version }}  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Generate the OAS schemas in another workflow
  oas-fetch:
    needs: update_release_draft
    uses: ./.github/workflows/fetch-oas.yml
    with:
      version: ${{ github.event.inputs.version }} 
    secrets: inherit
  # Upload the OAS schemas to the release object
  add-oas-to-release:
    needs: 
      - update_release_draft
      - oas-fetch
    runs-on: ubuntu-latest
    steps:
      - name: Load OAS files from artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: oas-*

      - name: Upload Release Asset - OpenAPI Specification - YAML
        id: upload-release-asset-yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
          asset_path: ./oas-yaml/oas.yaml
          asset_name: oas.yaml
          asset_content_type: application/vnd.oai.openapi

      - name: Upload Release Asset - OpenAPI Specification - JSON
        id: upload-release-asset-json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.update_release_draft.outputs.upload_url }}
          asset_path: ./oas-json/oas.json
          asset_name: oas.json
          asset_content_type: application/json

    
