name: "Release-2: Tag, Release, Push"

env:
  GIT_USERNAME: "DefectDojo release bot"
  GIT_EMAIL: "dojo-release-bot@users.noreply.github.com"
  workflow_name: 'release 2 tag release docker push' # needed in cache key, which doesn't support comma's
on:
  workflow_dispatch:
    inputs:
      # the actual branch that can be chosen on the UI is made irrelevant by further steps
      # because someone will forget one day to change it.
      release_number:
        description: 'Release version (x.y.z format)'
        required: true

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Configure git
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"

      - name: Create new tag ${{ github.event.inputs.release_number }}
        # at this point, the PR from the 1st workflow is merged into master.
        run: |
          git tag -a ${{ github.event.inputs.release_number }} -m "[bot] release ${{ github.event.inputs.release_number }}"
          git push origin ${{ github.event.inputs.release_number }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.4.0

      - name: Configure Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dependency list ./helm/defectdojo
          helm dependency update ./helm/defectdojo

      - name: Package Helm chart
        id: package-helm-chart
        run: |
          mkdir build
          helm package helm/defectdojo/ --destination ./build
          echo "chart_version=$(ls build | cut -d '-' -f 2 | sed 's|\.tgz||')" >> $GITHUB_ENV

      - name: Create release ${{ github.event.inputs.release_number }}
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.event.inputs.release_number }}
          tag_name: ${{ github.event.inputs.release_number }}
          body: Run the release drafter to populate the release notes.
          draft: true
          prerelease: false
          files: ./build/defectdojo-${{ env.chart_version }}.tgz
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_REPOSITORY: DefectDojo/django-DefectDojo

      - name: Update Helm repository index
        id: update-helm-repository-index
        run: |
          git config --global user.name "${{ env.GIT_USERNAME }}"
          git config --global user.email "${{ env.GIT_EMAIL }}"
          git remote update
          git fetch --all
          git checkout helm-charts
          git pull
          if [ ! -f ./index.yaml ]; then
            helm repo index ./build --url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${{ github.event.inputs.release_number }}/"
          else
            helm repo index ./build --url "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases/download/${{ github.event.inputs.release_number }}/" --merge ./index.yaml
          fi
          cp -f ./build/index.yaml ./index.yaml
          git add ./index.yaml
          git commit -m "Update index.yaml"
          git push -u origin helm-charts


  job-build-and-push:
    needs: tag-and-release
    runs-on: ubuntu-latest
    strategy:
      matrix:
          docker-image: [django, nginx]
          os: [alpine, debian]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.release_number }}

      - id: set-repo-org
        run: echo "repoorg=$(echo ${GITHUB_REPOSITORY%%/*} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        env:
          docker-image: ${{ matrix.docker-image }}
        with:
          path: /tmp/.buildx-cache-${{ env.docker-image }}
          key: ${{ runner.os }}-buildx-${{ env.docker-image }}-${{ matrix.os }}-${{ env.workflow_name }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ env.docker-image }}-${{ matrix.os }}-${{ env.workflow_name}}-${{ github.sha }}
            ${{ runner.os }}-buildx-${{ env.docker-image }}-${{ matrix.os }}-${{ env.workflow_name }}
            ${{ runner.os }}-buildx-${{ env.docker-image }}-${{ matrix.os }}-

      - name: Build and push images with debian
        uses: docker/build-push-action@v4
        if: ${{ matrix.os }} == 'debian'
        env:
          REPO_ORG: ${{ env.repoorg }}
          docker-image: ${{ matrix.docker-image }}
        with:
          push: true
          if: ${{ matrix.os }} == 'debian'
          tags: ${{ env.REPO_ORG }}/defectdojo-${{ env.docker-image}}:${{ github.event.inputs.release_number }}-${{ matrix.os }}, ${{ env.REPO_ORG }}/defectdojo-${{ env.docker-image}}:${{ github.event.inputs.release_number }}, ${{ env.REPO_ORG }}/defectdojo-${{ env.docker-image}}:latest
          file: ./Dockerfile.${{ env.docker-image }}-${{ matrix.os }}
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache-${{ env.docker-image }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ env.docker-image }}

      - name: Build and push images with alpine
        uses: docker/build-push-action@v4
        if: ${{ matrix.os }} == 'alpine'
        env:
          REPO_ORG: ${{ env.repoorg }}
          docker-image: ${{ matrix.docker-image }}
        with:
          push: true
          if: ${{ matrix.os }} == 'alpine'
          tags: ${{ env.REPO_ORG }}/defectdojo-${{ env.docker-image}}:${{ github.event.inputs.release_number }}-${{ matrix.os }}
          file: ./Dockerfile.${{ env.docker-image }}-${{ matrix.os }}
          context: .
          cache-from: type=local,src=/tmp/.buildx-cache-${{ env.docker-image }}
          cache-to: type=local,dest=/tmp/.buildx-cache-${{ env.docker-image }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
