name: Ruff Linter

on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      
      - name: Install Ruff Linter
        run: pip install -r requirements-lint.txt

      - name: Run Ruff Linter
        run: ruff check --output-format=github .
