name: Ruff Linter

on:
  workflow_dispatch:
  push:
  pull_request:
jobs:
  ruff-linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      
      - name: Install Ruff Linter
        run: pip install -r requirements-lint.txt

      - name: Run Ruff Linter
        run: ruff check --output-format=github .
